#!/bin/bash

# Remove a package from system
. /usr/local/lib/liblake_common

usage() {
    echo "usage: $(basename $0) pkgfname"
}

if [ $# -ne 1 ]; then
    usage
    exit E_WARGS
fi

pkgfname=$1
pkgname=${pkgfname%-*}
cmdfile=$pkgfname

cat >> $cmdfile <<EOF
#!/bin/bash

pkgfname=$pkgfname
pkgname=$pkgname
EOF

cat >> $cmdfile <<'EOF'
build=$(pwd)
logdir=$build/log
logfile=$logdir/$pkgfname
fakeroot=$build/pkgroot

mkdir -p $logdir $fakeroot &&
. /usr/local/lib/build_funcs &&

function patch_cmd()
{
    :
}

function configure_cmd()
{
    ./configure --prefix=/usr
}

function make_cmd()
{
    make -j4
}

function check_cmd()
{
    make check
}

function install_cmd()
{
    make install
}

EOF

cat >> $cmdfile <<EOF
function cleanup_cmd()
{
    cd \$build &&
    rm -r ${pkgname}/
}

EOF

cat >> $cmdfile <<'EOF'
cd $build &&
tar xf ${pkgname}.tar &&
#run_cmd "${logfile}-patch" 'patch_cmd' &&
run_cmd "${logfile}-conf" 'configure_cmd' &&
run_cmd "${logfile}-make" 'make_cmd' &&
run_cmd "${logfile}-check" 'check_cmd' &&
run_cmd "${logfile}-install" 'install_cmd' &&
#run_cmd "${logfile}-cleanup" 'cleanup_cmd' &&
echo succeed || { echo failed; exit 1; }
EOF
