#!/bin/bash

# Make a packed package. Execute command file, generate file list, handle $info/dir. Maybe custom etcs?

. /usr/local/lib/liblake_common
#check_commondirs

usage() {
    echo "usage: $(basename $0) [options] cmdfile"
    echo "options: -n: no execute, take cmdfile as pkgfname"
}

gen_list() {
    if [ -e $list -a ! -f $list ]
    then
        echo "$file not a regular file"
        exit $E_BADFILE
    fi

    find $dir/ > $list
    sed -i "s@^$dir/@@" $list
    sed -i "/^$/d" $list
}

case "$1" in
    -h)
        usage
        exit
        ;;
    -n)
        execute=no
        shift
        ;;
esac

if [ $# -lt 1 ]; then
    usage
    exit $E_WARGS
fi

if [ ! -e $1 ]; then
    echo "cmdfile $1 not exists"
    exit $E_BADDIR
fi

cmdfile=$1
pkgfname=${cmdfile%.}
pkg=${pkgfname}.pkg
dir=pkgroot
list=.LIST

if [ -e $pkg.bz2 ]; then
    echo $pkg.bz2 exists
    echo -n "$pkg.bz2 exists. Remove it? "
    read ans
    case "$ans" in
        Y|y)
            rm $pkg.bz2
            echo "$pkg.bz2 removed."
            ;;
        N|n)
            echo "Exiting..."
            exit
            ;;
        *)
            echo "Unknown cmd $ans. Exiting."
            exit $E_BADRESPONSE
            ;;
    esac
fi

if [ _$execute != _no ]; then
    if [ -e $dir ]; then
        if [ ! -d $dir ]; then
            echo $dir not a directory
            exit $E_BADDIR
        else
            echo -n "$dir exists. Remove it? "
            read ans
            case "$ans" in
                Y|y)
                    rm -r $dir
                    echo "$dir removed."
                    ;;
                N|n)
                    echo "Exiting..."
                    exit
                    ;;
                K|k)
                    echo "$dir kept."
                    ;;
                *)
                    echo "Unknown cmd $ans. Exiting."
                    exit $E_BADRESPONSE
                    ;;
            esac
        fi
    fi
    sh $cmdfile || exit $E_CMDFAILED
fi

if [ ! -d $dir ]; then
    echo "$dir not a directory. Exiting..."
    exit $E_BADDIR
fi

if [ -f $dir/$infodir/dir ]; then
    rm $dir/$infodir/dir
fi

gen_list

if [ ! -f $list ]; then
    echo "$list not a file. Exiting..."
    exit $E_BADFILE
fi

tar -cf $pkg $list -C $dir . || exit $E_CMDFAILED
bzip2 -z $pkg || exit $E_CMDFAILED
