#!/bin/bash

# Make a packed package. Execute command file, generate file list, handle $info/dir. Maybe custom etcs?

. /usr/local/lib/liblake_common

usage() {
    echo "usage: $(basename $0) [options] cmdfile"
    echo "options: -n: no execute, take cmdfile as pkgfname"
}

gen_list() {
    if [ -e $list -a ! -f $list ]
    then
        echo "$file not a regular file"
        exit $E_BADFILE
    fi

    find $dir/ > $list
    sed -i "s@^$dir/@@" $list
    sed -i "/^$/d" $list
}

case "$1" in
    -h)
        usage
        exit
        ;;
    -n)
        execute=no
        shift
        ;;
esac

if [ $# -lt 1 ]; then
    usage
    exit $E_WARGS
fi

if [ ! -e $1 ]; then
    echo "cmdfile $1 not exists"
    exit $E_BADDIR
fi

cmdfile=$1
pf=${cmdfile%.}
pkg=${pf}.pkg
dir=pkgroot
list=.LIST

if [ -e $pkg -o -e $pkg.bz2 ]; then
    echo $pkg exists
    exit
fi

sh $cmdfile || exit $E_CMDFAILED

if [ ! -d $dir ]; then
    echo "$dir not a directory. Exiting..."
    exit $E_BADDIR
fi

gen_list

if [ ! -f $list ]; then
    echo "$list not a file. Exiting..."
    exit $E_BADFILE
fi

tar -cf $pkg $list -C $dir . || exit $E_CMDFAILED
bzip2 -z $pkg || exit $E_CMDFAILED
