#!/bin/bash

# Remove a package from system

. /usr/local/lib/liblake_common

usage() {
    echo "usage: $(basename $0) pkgfname"
}

if [ $# -ne 1 ]; then
    usage
    exit $E_WARGS
fi

check_commondirs

# Definitions. Main routine begins at line 219

parse_list() {
    local file

    # check for info
    grep "\.info$" $list > $info
}

rm_info() {
    if [ -s $info ]; then
        local infofile
        echo "Updating $infodir/dir..."
        while read infofile
        do
            echo "Remove $infofile"
            install-info --remove /$infofile $infodir/dir
        done < $info
        echo done
    fi
    rm $info
}

pkgfname=$1
listname=${pkgfname}.list
list=$currents/$listname
info=$(mktemp)

if [ ! -e $list ]
then
    echo "Package $pkgfname not installed"
    exit $E_NOTINSTALLED
fi

echo $list

parse_list

if [ -f $info ]; then
    rm_info $info
fi

tac $list | while read file
do
    if [ ! -e /$file -a ! -L /$file ]
    then
        echo /$file not found
    elif [ -d /$file ]
    then
        if [ ! "$(ls -A /$file)" ]
        then
            echo remove /$file
            rm -r /$file
        else
            echo directory /$file not empty, leave it alone
        fi
    else
        echo remove /$file
        rm /$file
    fi
    sed -i "$ d" $list
done

rm $list
